
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: service

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
plugins:
  - serverless-webpack
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs4.3
  profile: santiment
  region: eu-central-1

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  getSentiment:
    handler: handler.getSentiment

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
    events:
      - http:
          path: sentiment
          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending

#    Define function environment variables here
#    environment:
#      variable2: value2
  postSentiment:
    handler: handler.postSentiment
    events:
      - http:
          path: sentiment
          method: post

  getAggregateSentiment:
    handler: handler.getAggregateSentiment
    events:
      - http:
          path: sentiment/aggregate
          method: get

  getFeed:
    handler: handler.getFeed
    events:
      - http:
          path: feed
          method: get
    vpc:
      securityGroupIds:
        - sg-c209b4a9
      subnetIds:
        - subnet-ff530597
    environment:
      ELASTICSEARCH_HOST: internal-elasticsearch-elb-1302221820.eu-central-1.elb.amazonaws.com

# you can add CloudFormation resource templates here
resources:
  Resources:
    sentimentLogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sentimentLogTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: receivedTimestamp
            AttributeType: S
          - AttributeName: asset
            AttributeType: S
          - AttributeName: submittedTimestamp
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: receivedTimestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: SentimentByAssetIndex
            KeySchema:
              - AttributeName: asset
                KeyType: HASH
              - AttributeName: submittedTimestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 2
              WriteCapacityUnits: 2

#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
custom:
  webpackIncludeModules: true
  dynamodb:
    start:
      port: 8800
      inMemory: true
      migrate: true
      seed: true
